---
firewall_allowed_tcp_ports:
  - 22
  - 80
  # For NFS.
  - 111
  - 2049
firewall_allowed_udp_ports:
  - 111
  - 2049

firewall_additional_rules:
  - "iptables -A INPUT -p tcp --dport 4949 -s {{ groups.balancer[0] }} -j ACCEPT"

# Nginx configuration.
nginx_worker_processes: "4" # Set to number of CPU cores on Pi.
nginx_worker_connections: "512"
nginx_client_max_body_size: "64m"
nginx_keepalive_timeout: "65"
nginx_remove_default_vhost: true
nginx_vhosts: []

# Don't keep updating Drush once installed.
drush_keep_updated: false

# NFS configuration.
nfs_share_dir: /srv/nfs
nfs_exports: { "/srv/nfs *(rw,sync,no_root_squash,no_subtree_check)" }
# nfs_mount_dir: /mnt/nfs # defined in global vars file.

# Munin settings.
munin_node_allowed_ips:
  - "^{{ groups.balancer[0] | replace('.', '\\.') }}$"

# PHP configuration.
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_memory_limit: "128M"
php_max_execution_time: "240"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "128"
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 7
php_fpm_pm_start_servers: 4
php_fpm_pm_min_spare_servers: 2
php_fpm_pm_max_spare_servers: 4
php_conf_paths:
  - /etc/php5/fpm
  - /etc/php5/cli
php_extension_conf_paths:
  - /etc/php5/fpm/conf.d
  - /etc/php5/cli/conf.d

# PHP source installation configuration.
#php_install_from_source: true
php_install_from_source: false
# Some example versions to try: php-5.6.29, php-7.0.17, php-7.1.3.
php_source_version: "php-7.0.17"
php_source_make_command: "make --jobs={{ ansible_processor_count }}"
php_source_install_gmp_path: "/usr/include/arm-linux-gnueabihf/gmp.h"
php_source_configure_command: >
  ./configure
  --prefix={{ php_source_install_path }}
  --with-config-file-path={{ php_conf_paths | first }}
  --with-config-file-scan-dir={{ php_conf_paths | first }}/conf.d
  --enable-mbstring
  --enable-zip
  --enable-bcmath
  --enable-pcntl
  --enable-ftp
  --enable-fpm
  --enable-exif
  --enable-calendar
  --enable-opcache
  --enable-pdo
  --enable-sysvmsg
  --enable-sysvsem
  --enable-sysvshm
  --enable-wddx
  --with-curl
  --with-mcrypt
  --with-iconv
  --with-gmp
  --with-pspell
  --with-gd
  --with-jpeg-dir=/usr
  --with-png-dir=/usr
  --with-zlib-dir=/usr
  --with-xpm-dir=/usr
  --with-freetype-dir=/usr
  --enable-gd-native-ttf
  --enable-gd-jis-conv
  --with-openssl
  --with-pdo-mysql=/usr
  --with-gettext=/usr
  --with-zlib=/usr
  --with-bz2=/usr
  --with-recode=/usr
  --with-mysqli=/usr/bin/mysql_config
