---
- name: Mass Update and Upgrade Ubuntu Hosts
  hosts: masters  # Specify your inventory group or individual hosts
  become: true  # Use sudo to run the commands
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Upgrade all installed packages to the latest version
      apt:
        upgrade: dist  # Use 'dist' to perform a full upgrade; use 'yes' for a safe upgrade

    - name: Remove unnecessary packages
      apt:
        autoremove: yes  # Removes packages that were automatically installed to satisfy dependencies

    - name: Clean up apt cache
      apt:
        autoclean: yes  # Clean up the local repository of retrieved package files

