---
- name: Run existing InstallHA.sh script on remote host
  hosts: masters
  become: yes
  tasks:
    - name: Ensure InstallHA.sh has executable permissions
      file:
        path: /home/ubuntu/01_HAProxy/InstallHA.sh
        mode: '0755'

    - name: Execute InstallHA.sh on remote host
      shell: "sh /home/ubuntu/01_HAProxy/InstallHA.sh"
      args:
        executable: /bin/bash

