---
- name: Execute shell script on remote server to install Keepalived & HAProxy
  hosts: masters
  become: true
  tasks:
    - name: Run shell script on remote server to install Keepalived & HAProxy
      shell: "sh /home/ubuntu/0_HAProxy/InstallHA.sh"
      async: 1
      poll: 0
      ignore_errors: true

