---
# To run:
#   $ ansible-playbook -i ../../inventory drupal.yml

- hosts: webservers
  gather_facts: no
  become: yes

  vars_files:
    - ../../config.yml

  tasks:
    - name: Remove any Drupal downloads.
      shell: "rm -rf ~/drupal*"

    - name: Remove /var/www/drupal contents.
      shell: "rm -rf {{ drupal_docroot }}"

    - name: Remove shared files directory.
      shell: "rm -rf {{ nfs_mount_dir }}/files"
      when: "inventory_hostname == groups.webservers[0]"

    - name: Remove drupal_install_complete file.
      shell: "rm -rf /var/local/drupal_install_complete"

    - name: Remove Drupal cron job.
      cron:
        name: "Dramble Drupal cron"
        user: "{{ ansible_ssh_user }}"
        job: "/usr/local/bin/drush --quiet --root={{ drupal_docroot }} cron -y"
        state: absent
      when: "inventory_hostname == groups.webservers[0]"

    - name: Restart php-fpm and nginx.
      service: "name={{ item }} state=restarted"
      with_items:
        - php-fpm
        - nginx

- hosts: database
  gather_facts: no
  become: yes

  vars_files:
    - ../../playbooks/database/vars.yml
    - ../../config.yml

  tasks:
    - name: Drop the drupal database.
      shell: "echo 'DROP DATABASE IF EXISTS {{ mysql_databases[0]['name'] }};' | mysql -u root -p{{ mysql_root_password }}"

- hosts: balancer
  gather_facts: no
  become: yes

  vars_files:
    - ../../config.yml

  tasks:
    - name: Empty nginx reverse proxy cache.
      shell: "rm -rf /var/cache/nginx/*"

    - name: Restart nginx.
      service: name=nginx state=restarted
