---
- name: restart nginx
  service: name=nginx state=restarted
  notify: restart php-fpm

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: purge reverse proxy cache
  shell: "rm -rf /var/cache/nginx/*"
  delegate_to: "{{ item }}"
  with_items: groups.balancer
