---
- name: Copy vhost configuration into place.
  template:
    src: ../templates/drupal.conf.j2
    dest: /etc/nginx/sites-enabled/drupal.conf
    mode: 0644
  notify: restart nginx

- name: Ensure pi user is in www-data group.
  user:
    name: pi
    groups: www-data
    append: yes
