---
- name: Ensure dependencies are installed.
  apt: "name={{ item }} state=present"
  with_items:
    # Needed to complete Drupal installation.
    - sendmail-bin
    - sendmail
    # So drush can connect to MySQL.
    - mysql-client
